#include "radioconf.h"

// parts that should be transmitting in each time slot
const char TXtimeTable[] = {
	ANCHOR1_ID,
	BIGFOE_ID,
	BIGFOE_ID,
	BIGFOE_ID,
	BIGFOE_ID,
	SMALLFOE_ID,
	SMALLFOE_ID,
	SMALLFOE_ID,
	SMALLFOE_ID,
	BIGBOT_ID,
	BIGBOT_ID,
	BIGBOT_ID,
	BIGBOT_ID
};

// parts that should be listening in each time slot
const char RXtimeTable[] = {
	ANCHOR2_ID | ANCHOR3_ID | SMALLFOE_ID | BIGFOE_ID | BIGBOT_ID | LOGBOT_ID,
	ANCHOR3_ID,
	ANCHOR2_ID,
	ANCHOR1_ID,
	BIGBOT_ID | ANCHOR1_ID | ANCHOR2_ID | ANCHOR3_ID | LOGBOT_ID,
	ANCHOR3_ID,
	ANCHOR2_ID,
	ANCHOR1_ID,
	BIGBOT_ID | ANCHOR1_ID | ANCHOR2_ID | ANCHOR3_ID | LOGBOT_ID,
	ANCHOR3_ID,
	ANCHOR2_ID,
	ANCHOR1_ID,
	ANCHOR1_ID | ANCHOR2_ID | ANCHOR3_ID | BIGFOE_ID | SMALLFOE_ID | LOGBOT_ID
};
