#include "radioconf.h"

// parts that should be transmitting in each time slot
const char TXtimeTable[] = {
	BEACON1_ID,
  BEACON1_ID,
  BEACON2_ID,
  BEACON3_ID,
  BIGFOE_ID,
  SMALLFOE_ID,
  BIGBOT_ID
};

// parts that should be listening in each time slot
const char RXtimeTable[] = {
	BEACON2_ID | BEACON3_ID | SMALLFOE_ID | BIGFOE_ID | BIGBOT_ID,
	SMALLFOE_ID | BIGFOE_ID | BIGBOT_ID,
	SMALLFOE_ID | BIGFOE_ID | BIGBOT_ID,
	SMALLFOE_ID | BIGFOE_ID | BIGBOT_ID,
  BEACON1_ID | BEACON2_ID | BEACON3_ID | BIGBOT_ID,
  BEACON1_ID | BEACON2_ID | BEACON3_ID | BIGBOT_ID,
  BEACON1_ID | BEACON2_ID | BEACON3_ID
};

const int timeslotTable[] = {
  0,
  TIMESLOT_LENGTH,
  TIMESLOT_LENGTH + DS_TWR_LENGTH,
  TIMESLOT_LENGTH + 2*DS_TWR_LENGTH,
  TIMESLOT_LENGTH + 3*DS_TWR_LENGTH,
  2*TIMESLOT_LENGTH + 3*DS_TWR_LENGTH,
  3*TIMESLOT_LENGTH + 3*DS_TWR_LENGTH
};
